### ISSUE TITLE
[Superthread] Misc. leftover bugs

### ISSUE THREAD

**Issue by andrewkchan** [codebase-berkeley-mentored-project-fa17/ApplicationPortal#32]
This is an incomplete list of bugs left over from the last commit of the semester. We can add to this as we find new bugs.

- [x] Click to change rating successfully changes rating in DB, but changes not reflected until refresh
- [ ] Garbage can icon to delete comment does nothing
- [x] Clicking any of the "Move to category", "Assign to user" dropdowns opens up all of the dropdowns (??)
- [x] Move to category button on the individual application view displays categories correctly, but doesn't actually move the application anymore.
- [ ] Various styling issues when editing a category name (the whole page's font changes, some margins get messed up, etc.)
- [x] All templates should be in a specific folder. We should have some folders and some templates hanging around
- [x] All the views should be in the views folder. We shouldn't have a views folder and a views.py file
- [x] We should consider breaking up the urls.py file as well
- [x] Get rid of all js in html files and move to an external sheet

**Comment by bdeleonardis1** [comment]
When I click the garbage can icon it does delete it... Were you trying to delete someone else's comment?

**Comment by bdeleonardis1** [comment]
Still a little busy work to be done on responsive stars. I hate the annoying outline on the star and the solution to getting application id is hacky and ugly. But it works.

**Comment by bdeleonardis1** [comment]
The edit category name problem is being caused because that reloads a completely new HTML page. Someone must've copy and pasted 130 lines of HTML from dashboard.html LOL. Create category is the same thing - completely new html page. Once we fix this and only have a category.html page it should go in the dashboard folder and we can delete the category folder
