### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by bdeleonardis1** [codebase-berkeley-mentored-project-fa17/ApplicationPortal#37]
That little thing that shows up in the tab. Steal from codebase.berkeley.edu

**Comment by brianlevis** [comment]
[I have contributed](https://github.com/codebase-berkeley/ApplicationPortal/tree/favicon)

**Comment by andrewkchan** [comment]
@brianlevis you need to fork from staging not master

**Comment by brianlevis** [comment]
Okeley dokeley
[link](https://github.com/codebase-berkeley/ApplicationPortal/pull/44)

**Comment by andrewkchan** [comment]
Litty thanks!
